# Taller preparcial 1 — Sección 3: Pandas
**Ciencia de Datos · Programación II · Universidad Externado de Colombia**

## Instrucciones de entrega (GitHub)
1. Cree un repositorio en GitHub desde su cuenta asociada a su **correo institucional**.
2. Abra el repositorio en **GitHub Codespaces** y suba/cree este cuaderno.
3. Desarrolle cada punto en la celda de código que le sigue.
4. Realice **un commit por cada punto desarrollado**, con un mensaje claro, por ejemplo: `Subseccion 1 - Punto 3: estandarizar Genero`.

## Instrucciones del taller
Resuelva cada punto escribiendo el código en Python/pandas necesario. **A partir de la subsección 2, todas las preguntas asumen que el DataFrame ya fue limpiado con las soluciones de la subsección 1** (salvo que se indique explícitamente lo contrario).

## Contexto
Considere el siguiente `DataFrame` `df`, con información de 12 empleados de una empresa. Ejecute la siguiente celda para crearlo.

In [146]:
import pandas as pd
import numpy as np

datos = {
    "Nombre": ["Mariana", "Esteban", "Camilo", "Juliana", "Nicolas", "Paula",
               "Sebastian", "Laura", "Andres", "Catalina", "Esteban", "Manuela"],
    "Edad": [24, 29, 35, 22, 31, 27, 40, 26, 33, 29, 29, 24],
    "Genero": ["Mujer", "H", "Hombre", "M", "Hombre", "Mujer",
               "H", "Mujer", "Hombre", "M", "H", "Mujer"],
    "Ciudad": ["Bogota", "Medellin", "Cali", "Bogota", "Bucaramanga", "Medellin",
               "Bogota", "Cali", "Pasto", "Bogota", "Medellin", "Bogota"],
    "Departamento": ["Marketing", "Ventas", "IT", np.nan, "Ventas", "Marketing",
                     "IT", np.nan, "Finanzas", "Marketing", "Ventas", "Finanzas"],
    "Salario": [3.8, 4.2, 6.0, 3.2, 4.0, 3.9, 6.3, 3.7, 4.5, 55.0, 4.2, 3.6],
    "AñosExperiencia": [2, 5, 10, -3, 7, 4, 15, 3, 9, 6, 5, 2],
}

df = pd.DataFrame(datos)
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,H,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,M,Bogota,NaN,3.2,-3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,H,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,NaN,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,M,Bogota,Marketing,55.0,6
10,Esteban,29,H,Medellin,Ventas,4.2,5
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

Este conjunto de datos presenta **cinco** problemas de calidad, que se resolverán en la subsección 1.

> **Nota:** en `df` las ciudades están escritas sin tilde (`Medellin`). Tenga esto en cuenta al filtrar.

---
## Subsección 1: Limpieza de datos

**1.** La variable **Departamento** tiene valores faltantes (`NaN`) en las filas de **Juliana** y **Laura**. Escriba el código en pandas que impute estos valores utilizando la **moda** de la variable.

In [147]:
df["Departamento"].mode
df["Departamento"] = df["Departamento"].fillna(df["Departamento"].mode)

df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,H,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,M,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,-3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,H,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,M,Bogota,Marketing,55.0,6
10,Esteban,29,H,Medellin,Ventas,4.2,5
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

**2.** La variable **AñosExperiencia** tiene un valor negativo en la fila de **Juliana** (`-3`), producto de un error de digitación. Escriba el código en pandas que corrija este valor, convirtiéndolo en positivo.

In [148]:
# Escriba aquí su código
df.loc[df["Nombre"] == "Juliana", "AñosExperiencia"] = abs(df.loc[df["Nombre"] == "Juliana", "AñosExperiencia"])
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,H,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,M,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,H,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,M,Bogota,Marketing,55.0,6
10,Esteban,29,H,Medellin,Ventas,4.2,5
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

**3.** La variable **Genero** presenta inconsistencias: aparece registrada como `"Hombre"`, `"H"`, `"Mujer"` y `"M"`. Escriba el código en pandas que estandarice esta variable para que solo queden los valores `"Hombre"` y `"Mujer"`.

In [149]:
# Escriba aquí su código
df["Genero"] = df["Genero"].replace({"H": "Hombre","M": "Mujer"})

df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,Hombre,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,55.0,6
10,Esteban,29,Hombre,Medellin,Ventas,4.2,5
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

**4.** El `DataFrame` contiene una fila **duplicada**: el empleado **Esteban** aparece registrado dos veces de forma idéntica. Escriba el código en pandas que detecte y elimine las filas duplicadas.

In [150]:
# Escriba aquí su código
df = df.drop_duplicates()
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,Hombre,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,55.0,6
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

**5.** La variable **Salario** de **Catalina** tiene un valor atípico (`55.0`), muy alejado del resto de los datos. Corríjalo asumiendo que se trata de un error de digitación (un cero de más).

In [151]:
# Escriba aquí su código
df.loc[df["Nombre"] == "Catalina", "Salario"] = ( df.loc[df["Nombre"] == "Catalina", "Salario"] / 10)
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,Hombre,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,5.5,6
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

**6.** El registro de **Manuela** está desactualizado: en realidad ella tiene **8 años** de experiencia. Escriba el código en pandas que corrija ese dato.

In [152]:
# Escriba aquí su código
df.loc[df["Nombre"] == "Manuela", "AñosExperiencia"] = 8
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,Hombre,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,5.5,6
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,8

---
## Subsección 2: Exploración, filtrado, consultas, ordenamiento

**1.** Obtenga una descripción estadística completa de **todas** las variables del `DataFrame` ya limpio (tanto numéricas como categóricas).

In [153]:
df.describe()

            Edad    Salario  AñosExperiencia
count  11.000000  11.000000        11.000000
mean   29.090909   4.427273         6.545455
std     5.375026   1.037392         3.830500
min    22.000000   3.200000         2.000000
25%    25.000000   3.750000         3.500000
50%    29.000000   4.000000         6.000000
75%    32.000000   5.000000         8.500000
max    40.000000   6.300000        15.000000

In [154]:
df.describe(include="all")

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
count,11,11.000000,11,11,11,11.000000,11.000000
unique,11,NaN,2,5,5,NaN,NaN
top,Mariana,NaN,Mujer,Bogota,Marketing,NaN,NaN
freq,1,NaN,6,5,3,NaN,NaN
mean,NaN,29.090909,NaN,NaN,NaN,4.427273,6.545455
std,NaN,5.375026,NaN,NaN,NaN,1.037392,3.830500
min,NaN,22.000000,NaN,NaN,NaN,3.200000,2.000000
25%,NaN,25.000000,NaN,NaN,NaN,3.750000,3.500000
50%,NaN,29.000000,NaN,NaN,NaN,4.000000,6.000000
75%,NaN,32.000000,NaN,NaN,NaN,5.000000,8.500000
max,NaN,40.000000,NaN,NaN,NaN,6.300000,15.000000

**2.** Cree un nuevo `DataFrame` llamado `df_num` que contenga **únicamente** las variables numéricas del `DataFrame` original.

In [155]:
df_num=df.select_dtypes(include=["number"])
df_num

    Edad  Salario  AñosExperiencia
0     24      3.8                2
1     29      4.2                5
2     35      6.0               10
3     22      3.2                3
4     31      4.0                7
5     27      3.9                4
6     40      6.3               15
7     26      3.7                3
8     33      4.5                9
9     29      5.5                6
11    24      3.6                8

**3.** Escriba el código en pandas que filtre las personas que cumplen **todas** las siguientes condiciones, e indique cuántos registros la cumplen:

- Tienen edad **impar**, **y**
- además, (son de **Bogotá o** tienen un salario mayor a `4.0`).

In [156]:
df_filtro=df[(df["Edad"]%2!=0)&(df["Ciudad"]=="Bogotá")|(df["Salario"]>4.0)]
df_filtro

      Nombre  Edad  Genero    Ciudad Departamento  Salario  AñosExperiencia
1    Esteban    29  Hombre  Medellin       Ventas      4.2                5
2     Camilo    35  Hombre      Cali           IT      6.0               10
6  Sebastian    40  Hombre    Bogota           IT      6.3               15
8     Andres    33  Hombre     Pasto     Finanzas      4.5                9
9   Catalina    29   Mujer    Bogota    Marketing      5.5                6

In [157]:
len(df_filtro)

5

**4.** Escriba el código en pandas que permita saber cuántas personas son **mujeres**, **no** son de **Medellín**, y tienen un **salario mayor a 5.3**.

In [158]:
df_filtro2=df[(df["Genero"]=="Mujer")&(df["Ciudad"]!="Medellín")&(df["Salario"]>5.3)]
df_filtro2

     Nombre  Edad Genero  Ciudad Departamento  Salario  AñosExperiencia
9  Catalina    29  Mujer  Bogota    Marketing      5.5                6

In [159]:
len(df_filtro2)

1

**5.** Escriba el código en pandas que determine **cuántas personas** tienen un nombre que **termina en vocal**.

In [160]:
len(df[df["Nombre"].str.endswith(("a","e","i","o","u"))])

7

**6.** Escriba el código en pandas que muestre a los **3 empleados mejor pagados**, ordenados de mayor a menor salario.

In [161]:
df.sort_values(by="Salario",ascending=False).head(3)

      Nombre  Edad  Genero  Ciudad Departamento  Salario  AñosExperiencia
6  Sebastian    40  Hombre  Bogota           IT      6.3               15
2     Camilo    35  Hombre    Cali           IT      6.0               10
9   Catalina    29   Mujer  Bogota    Marketing      5.5                6

**7.** Escriba el código en pandas que ordene el `DataFrame` de forma **ascendente por Salario** y, en caso de empate, de forma **descendente por AñosExperiencia**.

In [162]:
df.sort_values(by=["Salario","AñosExperiencia"],ascending=[True, False])

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
3,Juliana,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,8
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,5.5,6
2,Camilo,35,Hombre,Cali,IT,6.0,10
6,Sebastian,40,Hombre,Bogota,IT,6.3,15

**8.** Los siguientes dos puntos deben resolverse **en el orden en que aparecen**, ya que cada uno parte del resultado del anterior.

**8 (a).** Agregue al `DataFrame` un nuevo registro, con los datos de un empleado ficticio de su elección (respetando las columnas existentes).

In [163]:
df = df.reset_index(drop=True)
nuevo = df.index.max() + 1
df.loc[nuevo] = {"Nombre": "Daniel","Edad": 28,"Genero": "Hombre","Ciudad": "Bogota","Departamento": "Marketing","Salario": 4.5,"AñosExperiencia": 4}
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,Hombre,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,5.5,6
10,Manuela,24,Mujer,Bogota,Finanzas,3.6,8
11,Daniel,28,Hombre,Bogota,Marketing,4.5,4

**8 (b).** Elimine el registro que agregó en el punto anterior.

In [164]:
df = df.iloc[:-1]
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,Hombre,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,5.5,6
10,Manuela,24,Mujer,Bogota,Finanzas,3.6,8

**9.** Escriba el código en pandas que convierta todos los valores de la columna **Nombre** a **mayúsculas**.

In [173]:
df["Nombre"]=df["Nombre"].str.upper()
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,MARIANA,24,Mujer,Bogota,Marketing,3.8,2
1,ESTEBAN,29,Hombre,Medellin,Ventas,4.2,5
2,CAMILO,35,Hombre,Cali,IT,6.0,10
3,JULIANA,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3
4,NICOLAS,31,Hombre,Bucaramanga,Ventas,4.0,7
5,PAULA,27,Mujer,Medellin,Marketing,3.9,4
6,SEBASTIAN,40,Hombre,Bogota,IT,6.3,15
7,LAURA,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3
8,ANDRES,33,Hombre,Pasto,Finanzas,4.5,9
9,CATALINA,29,Mujer,Bogota,Marketing,5.5,6
10,MANUELA,24,Mujer,Bogota,Finanzas,3.6,8

**10.** Cree una nueva variable llamada `SalarioPorAño`, que sea el resultado de dividir el **Salario** entre los **AñosExperiencia** de cada empleado.

In [177]:
df["SalarioPorAño"]=df["Salario"]/df["AñosExperiencia"]
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia,SalarioPorAño
0,MARIANA,24,Mujer,Bogota,Marketing,3.8,2,1.900000
1,ESTEBAN,29,Hombre,Medellin,Ventas,4.2,5,0.840000
2,CAMILO,35,Hombre,Cali,IT,6.0,10,0.600000
3,JULIANA,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3,1.066667
4,NICOLAS,31,Hombre,Bucaramanga,Ventas,4.0,7,0.571429
5,PAULA,27,Mujer,Medellin,Marketing,3.9,4,0.975000
6,SEBASTIAN,40,Hombre,Bogota,IT,6.3,15,0.420000
7,LAURA,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3,1.233333
8,ANDRES,33,Hombre,Pasto,Finanzas,4.5,9,0.500000
9,CATALINA,29,Mujer,Bogota,Marketing,5.5,6,0.916667
10,MANUELA,24,Mujer,Bogota,Finanzas,3.6,8,0.450000

**11.** Cree una nueva variable categórica llamada `Antiguedad`, a partir de **AñosExperiencia**, de la siguiente manera:

- `"nuevo"` si tiene **menos de 2 años** de experiencia.
- `"experto"` si tiene **entre 2 y 5 años** de experiencia (ambos incluidos).
- `"antiguo"` si tiene **6 años o más** de experiencia.

In [178]:
df["Antiguedad"]=df["AñosExperiencia"].apply(lambda x:"nuevo"if x<2 else "experto" if 2<=x<=5 else "antiguo")
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia,SalarioPorAño,Antiguedad
0,MARIANA,24,Mujer,Bogota,Marketing,3.8,2,1.900000,experto
1,ESTEBAN,29,Hombre,Medellin,Ventas,4.2,5,0.840000,experto
2,CAMILO,35,Hombre,Cali,IT,6.0,10,0.600000,antiguo
3,JULIANA,22,Mujer,Bogota,<bound method Series.mode of 0 Marketing\n...,3.2,3,1.066667,experto
4,NICOLAS,31,Hombre,Bucaramanga,Ventas,4.0,7,0.571429,antiguo
5,PAULA,27,Mujer,Medellin,Marketing,3.9,4,0.975000,experto
6,SEBASTIAN,40,Hombre,Bogota,IT,6.3,15,0.420000,antiguo
7,LAURA,26,Mujer,Cali,<bound method Series.mode of 0 Marketing\n...,3.7,3,1.233333,experto
8,ANDRES,33,Hombre,Pasto,Finanzas,4.5,9,0.500000,antiguo
9,CATALINA,29,Mujer,Bogota,Marketing,5.5,6,0.916667,antiguo
10,MANUELA,24,Mujer,Bogota,Finanzas,3.6,8,0.450000,antiguo

---
## Subsección 3: Agrupamiento (`groupby`)

Todas las preguntas de esta sección asumen que ya se creó la variable `Antiguedad` de la Subsección 2.

**1.** Calcule el **salario promedio** por `Departamento`, ordenado de mayor a menor.

In [214]:
df.groupby('Departamento')['Salario'].mean().sort_values(ascending=False)

Departamento
IT           6.15
Ventas       4.10
Finanzas     4.05
Marketing    4.02
Name: Salario, dtype: float64

**2.** Cuente cuántos empleados hay de cada `Genero`.

In [242]:
df['Genero'].value_counts()

Genero
Mujer     6
Hombre    5
Name: count, dtype: int64

**3.** Encuentre el salario **máximo** y **mínimo** en cada `Ciudad`.

In [170]:
# Escriba aquí su código

**4.** Calcule, para cada categoría de `Antiguedad`, el promedio de **AñosExperiencia** y de **Salario** al mismo tiempo.

In [171]:
# Escriba aquí su código

**5.** Cuente cuántos empleados hay en cada combinación de `Departamento` y `Genero`.

In [172]:
# Escriba aquí su código